In [1]:
#Import the library
import numpy as np

In [2]:
#Creating the array using zeros() and ones()
a = np.zeros((3,3))
b = np.ones((3,3))
print('a=',a)
print('b=',b)

a= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
b= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
#SavE arrays to binary file
np.save('file1.npy',(a,b))

In [ ]:
#Load data from binary file
c=np.load('file1.npy')
print(c)